### ISSUE TITLE
HLSL: SV_Position duplicates the vertex shader output structure

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#140]
Hi,

I've got the following shader that I compile into SPIR-V via glslang and then convert back to glsl with SPIRV-Cross.

```
struct DEFAULT_VS_IN 
{
    float4 position : POSITION;
};

struct DEFAULT_VS_OUT 
{ 
    float4 hwPosition : SV_Position;
};

DEFAULT_VS_OUT default_vx ( DEFAULT_VS_IN input ) 
{ 
    DEFAULT_VS_OUT output ;	
    output.hwPosition = input.position;
    return output; 
}
```
```
#version 450

struct DEFAULT_VS_IN
{
    vec4 position;
};

struct DEFAULT_VS_OUT
{
    vec4 hwPosition;
};

struct DEFAULT_VS_OUT_1
{
};
layout(location = 0) in vec4 position;
layout(location = 0) out DEFAULT_VS_OUT_1 _entryPointOutput;

DEFAULT_VS_OUT _default_vx(DEFAULT_VS_IN input)
{
    DEFAULT_VS_OUT output;
    output.hwPosition = input.position;
    return output;
}

void main()
{
    DEFAULT_VS_IN input;
    input.position = position;
    DEFAULT_VS_IN param = input;
    gl_Position = _default_vx(param).hwPosition;
}
```

As you can see it's duplicated the DEFAULT_VS_OUT structure and created a new one called DEFAULT_VS_OUT_1, but because there are no other members which are part of that structure it becomes empty, and that's tripping up the glsl shader compiler later on. I think this is an issue with SPIRV-Cross because the SPIRV that's generated correctly outputs a structure which I think is correct behavior.

**Comment by HansKristian-ARM** [comment]
Which glslang version are you on? I think this is a glslang bug which has been fixed, because I'm getting:

```
#version 450

struct DEFAULT_VS_IN
{
    vec4 position;
};

struct DEFAULT_VS_OUT
{
    vec4 hwPosition;
};

layout(location = 0) in vec4 position;

DEFAULT_VS_OUT _default_vx(DEFAULT_VS_IN _input)
{
    DEFAULT_VS_OUT _output;
    _output.hwPosition = _input.position;
    return _output;
}

void main()
{
    DEFAULT_VS_IN _input;
    _input.position = position;
    DEFAULT_VS_IN param = _input;
    gl_Position = _default_vx(param).hwPosition;
}
```

**Comment by redorav** [comment]
Oh right, I'm not on latest code from the repo. Let me recompile and try again. Thanks!

**Comment by redorav** [comment]
Right, so I've updated both glslang and SPIRV-Cross to absolute latest and I'm still getting this issue. My command line to glslangValidator is

glslangValidator.exe broken.hlsl -D -H -S vert -e default_vx -o broken.spv

My command line to SPIRVCross is just SPIRVCross broken.spv

Am I missing anything?

**Comment by HansKristian-ARM** [comment]
Ok, so it seems like newer glslang does this, so seems like a regression to me. I'll report a bug upstream here: https://github.com/KhronosGroup/glslang/issues/785, I don't think this is a SPIRV-Cross bug, unless proven otherwise.

**Comment by redorav** [comment]
Right that makes sense, I'll monitor that bug then. Thanks!

**Comment by HansKristian-ARM** [comment]
Closing issue in wait for glslang.

**Comment by HansKristian-ARM** [comment]
We'll need a workaround for this it seems.

**Comment by redorav** [comment]
Hi Hans,

Regarding this question, is there a way I can manually remove structs from my shader? It's stopping me from building my shaders properly. On some structures I can add dummy values but for some others I don't have that option. I could potentially check manually as a workaround whether structures have members perhaps and delete them in an extra pass? I don't know whether it's possible or how I would go about it in SPIRV-Cross. Thanks!

**Comment by HansKristian-ARM** [comment]
I'll probably have a stab at a workaround tomorrow.

**Comment by HansKristian-ARM** [comment]
Workaround in flight: https://github.com/KhronosGroup/SPIRV-Cross/pull/150

**Comment by HansKristian-ARM** [comment]
Merged.

**Comment by redorav** [comment]
Just to confirm that this works perfectly. Thanks a lot
